filebeat.inputs:
- type: filestream
  id: my-filestream-id
  paths:
    - '/usr/share/filebeat/logs/nginx/access.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}_%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
